### ISSUE TITLE
ReadableStream instead of FileDirLike?

### ISSUE THREAD

**Issue by Manouchehri** [Sec-ant/torrefy#6]
For large files, buffering the entire thing into an ArrayBuffer or Blob for `new File(...)` isn't always doable. Would it be possible to have `create([my_ReadableStream])` to avoid needing to buffer everything at once?

**Comment by Sec-ant** [comment]
Thanks for the suggestion.

If you know the size of the file, a simple solution is possible. We can define a new interface that structurally compatible with the File API (partially):

```ts
interface MyFile {
  name: string;
  size: number;
  webkitRelativePath: string;
  stream: () => ReableStream<Uint8Array>;
}
```

And you can put the your `ReadableStream` in the corresponding location.

Yet this new interface won't work in the current version.

A runnable patch in the current version would be something like this (not tested though):

```ts
const myFile = Object.create(File.prototype, {
  name: {
    value: "myFile.txt",
  },
  size: {
    value: 65536,
  },
  webkitRelativePath: {
    value: "",
  },
  stream: {
    value: () => myReadableStream,
  },
}) as File;
```

If you don't know the size in advance, it should still be possible, but I'll need to change several places in my code. This feature will be supported in the next major version, along with the async-iteration refactoring.

**Comment by Manouchehri** [comment]
I should always know the file size in advanced. =)

**Comment by Manouchehri** [comment]
Sweet, I can confirm your method works already. Looks like my torrents are functional!
